# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.16.1'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npx eslint --max-warinings=0 src || exit 1
  displayName: 'lint code'

- script: |
    npm test -- -- watchAll=false || exit 1
  displayName: 'unit test'

- task: DownloadSecureFile@1
  displayName: 'Download Settings'
  inputs:
    secureFile: 'settings_scrd.xml'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: 'settings_scrd.xml'
    TargetFolder: '/home/vsts/.m2'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Test'
    codeCoverageToolOption: 'JaCoCo'
    codeCoverageFailIfEmpty: true
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: true
    #sonarQubeRunAnalysis: true
    #sqMavenPluginVersionChoice: 'latest'